# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52275db4a0744a30084acfe75963b33e21a1b19a8be9e8547a69eb359977d69ebd83aef0bc2af4cf13e2fc64bb069f954544c45a2e5e0279a67626c34d6fc57e

test:
  secret_key_base: b7eee5d4ab91b1499f8be839ac0b1706a35f3f0e798db3bc5edbcd3c31f7ca496cedd25320a1306c85dd65eb3be10bd7e2de3c9b50eccd76d6425453a3c115e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
